Web-ban-hang/ViewModels/Customer.cs
namespace Web_ban_hang.ViewModels
{
    public class Customer
    {
        public string MaKh { get; set; } = null!;
        public string? MatKhau { get; set; }
        public string HoTen { get; set; } = null!;
        public bool GioiTinh { get; set; }
        public DateTime NgaySinh { get; set; }
        public string? DiaChi { get; set; }
        public string? DienThoai { get; set; }
        public string Email { get; set; } = null!;
        public string? Hinh { get; set; }
        public bool HieuLuc { get; set; }
    }
}

Web-ban-hang/Areas/Admin/Controllers/CustomerController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Web_ban_hang.Helpers;
using Web_ban_hang.Models.Entities;
using Web_ban_hang.ViewModels;

namespace Web_ban_hang.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CustomerController : Controller
    {
        private readonly HDangShopContext _context;
        private readonly IMapper _mapper;
    
        public CustomerController(HDangShopContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public IActionResult Edit(string id)
        {
            var customerss = _context.KhachHangs.FirstOrDefault(p => p.MaKh == id);

            // Ánh xạ từ đối tượng KhachHang sang CustomerViewModel
            var customerViewModel = _mapper.Map<Customer>(customerss);

            return View(customerViewModel);
        }

        [HttpPost]
        public IActionResult Edit(Customer model, IFormFile? Hinh)
        {
            var cus = _context.KhachHangs.SingleOrDefault(p => p.MaKh == model.MaKh);

            cus.MatKhau = model.MatKhau;
            cus.HoTen = model.HoTen;
            cus.DiaChi = model.DiaChi;
            cus.DienThoai = model.DienThoai;
            cus.Email = model.Email;
            cus.GioiTinh = model.GioiTinh;
            cus.NgaySinh = model.NgaySinh;
            cus.HieuLuc = model.HieuLuc;

            if (Hinh != null)
            {
                cus.Hinh = Util.UploadHinh(Hinh, "KhachHang");
            }
            TempData["Success"] = "Sửa khách hàng thành công";
            _context.SaveChanges();
            return RedirectToAction("Customer","databoard");
        }

        public IActionResult LockAcc(string id)
        {
            var cus = _context.KhachHangs.SingleOrDefault(p => p.MaKh == id);
            if (cus.HieuLuc == true)
            {
                cus.HieuLuc = false;
            }
            else
            {
                cus.HieuLuc= true;
            }

            TempData["Success"] = "Cập nhật tài khoản khách hàng thành công";
            _context.SaveChanges();

            return RedirectToAction("Customer", "databoard");

        }
    }    
}

Web-ban-hang/Areas/Admin/Controllers/DataBoardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using Web_ban_hang.Helpers;
using Web_ban_hang.Models.Entities;
using Web_ban_hang.Services;
using Web_ban_hang.ViewModels;
using X.PagedList.Extensions;

namespace Web_ban_hang.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DataBoardController : Controller
    {
        private readonly HDangShopContext db;
        private readonly IMapper _mapper;


        public DataBoardController(HDangShopContext context, IMapper mapper)
        {
            db = context;
            _mapper = mapper;
        }


        public IActionResult Index()
        {
            var data = db.ChiTietHds.Include(p => p.MaHdNavigation).Include(p => p.MaHdNavigation.MaKhNavigation)
               .OrderByDescending(o => o.MaHdNavigation.NgayDat)
               .ToList()
               .Where(p => p.MaHdNavigation.MaTrangThai == 1);

            ViewBag.Todaysale = db.ChiTietHds.Include(p => p.MaHdNavigation).Where(p => p.MaHdNavigation.NgayDat.Date == DateTime.Now.Date).Sum(p => p.SoLuong * p.DonGia);
            ViewBag.Totalsale = db.ChiTietHds.Include(p => p.MaHdNavigation).Sum(p => (p.SoLuong * p.DonGia) * (1 - p.GiamGia));
            ViewBag.SoHH = db.ChiTietHds.Include(p => p.MaHdNavigation).Where(p => p.MaHdNavigation.NgayDat.Date == DateTime.Now.Date).Sum(p => p.SoLuong);
            ViewBag.TotalOrder = db.HoaDons.Where(p => p.NgayDat.Date == DateTime.Now.Date).Count();


            var result = data.Select(item => new InvoiceVM
            {
                MaHD = item.MaHd,
                HoTen = item.MaHdNavigation.MaKhNavigation.HoTen,
                TongTien = (item.DonGia * item.SoLuong) * (1 - item.GiamGia),
                NgayDat = item.MaHdNavigation.NgayDat,
                TrangThai = item.MaHdNavigation.MaTrangThai,
            }).ToList().DistinctBy(p => p.MaHD).Take(5);





			var revenueData = db.ChiTietHds
	.Where(ct => ct.MaHdNavigation != null) // Đảm bảo có hóa đơn
	.GroupBy(ct => ct.MaHdNavigation.NgayDat.Date)
	.Select(g => new
	{
		Ngay = g.Key,
		DoanhThu = g.Sum(ct => ct.SoLuong * ct.DonGia) // Tính tổng doanh thu từ chi tiết hóa đơn
	}).Take(7)
	.OrderByDescending(r => r.Ngay)
	.ToList();

			// Chuyển dữ liệu sang JSON để sử dụng trong JavaScript
			var labels = revenueData.Select(r => r.Ngay.ToString("yyyy-MM-dd")).ToList();
            var dataChart = revenueData.Select(r => r.DoanhThu).ToList();

            // Gửi dữ liệu về View
            ViewBag.Labels = labels;
            ViewBag.Data = dataChart;



			var MonthrevenueData = db.ChiTietHds
	.Join(db.HoaDons, ct => ct.MaHd, hd => hd.MaHd, (ct, hd) => new { ct, hd })  // Thực hiện Join với HoaDon
	.Where(x => x.hd.NgayDat != null) // Đảm bảo có ngày đặt hàng
	.GroupBy(x => new { Year = x.hd.NgayDat.Year, Month = x.hd.NgayDat.Month }) // Nhóm theo năm và tháng
	.Select(g => new
	{
		Ngay = $"{g.Key.Month}/{g.Key.Year}", // Tạo chuỗi "MM/yyyy"
		DoanhThu = g.Sum(x => x.ct.SoLuong * x.ct.DonGia) // Tính doanh thu
	})
	/*.OrderByDescending(r => r.Ngay)*/ // Sắp xếp theo "MM/yyyy" giảm dần
	.Take(12) // Lấy 12 kết quả gần nhất
	.ToList();

			// Chuyển dữ liệu sang JSON để sử dụng trong JavaScript
			var labelsChart2 = MonthrevenueData.Select(r => r.Ngay).ToList();
			var dataChart2 = MonthrevenueData.Select(r => r.DoanhThu).ToList();

			// Gửi dữ liệu về View
			ViewBag.LabelsC2 = labelsChart2;
			ViewBag.DataC2 = dataChart2;




			return View(result);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginVM model)
        {
            if (ModelState.IsValid)
            {
                var khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == model.UserName);
                if (khachHang == null)
                {
                    ModelState.AddModelError("loi", "Không có admin này");
                        TempData["Error"] = "Tài khoản khong hợp lệ. ";

                }
                else
                {
                    if (!khachHang.HieuLuc || khachHang.VaiTro != 3)
                    {
                        ModelState.AddModelError("loi", "Tài khoản khong hợp lệ. ");
                        TempData["Error"] = "Tài khoản khong hợp lệ. ";
                    }
                    else
                    {
                        if (khachHang.MatKhau != model.Password.ToMd5Hash(khachHang.RandomKey) )
                        {
                            ModelState.AddModelError("loi", "Sai thông tin đăng nhập");
                        }
                        else
                        {
                            return Redirect("Index");
                        }
                    }
                }
            }

            return View();
        }

        public IActionResult InvoiceDetail(int? page)
        {
            var data = db.HoaDons.Include(p => p.MaKhNavigation)
                .OrderByDescending(o => o.NgayDat)
                .ToList();

            var result = data.Select(item => new InvoiceVM
            {
                MaHD = item.MaHd,
                HoTen = item.MaKhNavigation.HoTen,
                NgayCan = item.NgayCan ?? item.NgayDat,
                NgayDat = item.NgayDat,
                TrangThai = item.MaTrangThai,
            });

            // Thực hiện phân trang
            int pageSize = 20; // Số sản phẩm trên mỗi trang
            int pageNumber = page ?? 1; // Trang hiện tại, mặc định là trang 1
            var pagedResult = result.ToPagedList(pageNumber, pageSize);

            ViewBag.page = page;

            return View(pagedResult);
        }

        public IActionResult ViewOrder(int id)
        {
            var cthd = db.ChiTietHds.Include(p => p.MaHdNavigation).Include(p => p.MaHhNavigation).Where(p => p.MaHd == id).ToList();

            ViewBag.MaHD = id;
            //ViewBag.TenKH = db.ChiTietHds.Where(p => p.MaHd == id).FirstOrDefault().MaHdNavigation.HoTen;

            var chiTiet = db.HoaDons
    .Where(p => p.MaHd == id)
    .Include(p => p.MaKhNavigation)
    .FirstOrDefault();

            ViewBag.HoaDons = chiTiet;

            if (chiTiet != null && chiTiet.MaKhNavigation != null)
            {
                ViewBag.TenKH = chiTiet.MaKhNavigation.HoTen;
            }
            else
            {
                ViewBag.TenKH = "NULL";
            }


            var result = cthd.Select(data => new InvoiceVM
            {
                MaCT = data.MaCt,
                MaHD = data.MaHd,
                NgayDat = data.MaHdNavigation.NgayDat,
                MaKH = data.MaHdNavigation.MaKh,
                HoTen = data.MaHdNavigation.HoTen,
                DiaChi = data.MaHdNavigation.DiaChi,
                CachThanhToan = data.MaHdNavigation.CachThanhToan,
                GhiChu = data.MaHdNavigation.GhiChu,
                TrangThai = data.MaHdNavigation.MaTrangThai,
                TenSP = data.MaHhNavigation.TenHh,
                SoLuong = data.SoLuong,
                DonGia = data.DonGia,
                GiamGia = data.GiamGia,
            }).ToList();



            return View(result);
        }

        [HttpPost]
        public IActionResult ViewOrder(InvoiceVM model)
        {
            var data = db.ChiTietHds.Include(p => p.MaHdNavigation).SingleOrDefault(p => p.MaCt == model.MaCT);

            //data.MaHdNavigation.HoTen = model.HoTen;
            data.SoLuong = model.SoLuong;
            data.DonGia = model.DonGia;
            data.MaHdNavigation.MaTrangThai = model.TrangThai;
            data.MaHdNavigation.GhiChu = model.GhiChu;

            db.SaveChanges();

            return RedirectToAction("Index");

        }

        public IActionResult Product()
        {
            return RedirectToAction("Index");
        }
        public IActionResult Customer(int? page)
        {

            var customers = db.KhachHangs.ToList();

            var customerViewModels = _mapper.Map<List<Customer>>(customers);


            // Thực hiện phân trang
            int pageSize = 10; // Số sản phẩm trên mỗi trang
            int pageNumber = page ?? 1; // Trang hiện tại, mặc định là trang 1
            var pagedResult = customerViewModels.ToPagedList(pageNumber, pageSize);

            return View(pagedResult);
        }



        [HttpGet]
        public async Task<IActionResult> SearchAdmin(string? keyword)
        {

            if (string.IsNullOrEmpty(keyword))
                return View(new List<SearchResultViewModel>());

            // Tìm kiếm trong bảng Products
            var productResults = await db.HangHoas
                .Where(p => p.TenHh.Contains(keyword) || p.MoTa.Contains(keyword))
                .Select(p => new SearchResultViewModel
                {
                    Type = "Hàng hóa",
                    Title = p.TenHh,
                    Description = p.MoTa,
                    Link = $"/Admin/Product/Detail/{p.MaHh}",
                    srcImage = $"/Hinh/HangHoa/{p.Hinh}",
                }).ToListAsync();

            // Tìm kiếm trong bảng Categories
            var cusResult = await db.KhachHangs
                .Where(c => c.MaKh.Contains(keyword) || c.HoTen.Contains(keyword))
                .Select(c => new SearchResultViewModel
                {
                    Type = "Khách hàng",
                    Title = c.MaKh,
                    Description = c.HoTen,
                    Link = $"/Admin/Customer/Edit/{c.MaKh}",
                    srcImage = $"/Hinh/KhachHang/{c.Hinh}",

                }).ToListAsync();

            // Xử lý logic tìm kiếm
            var results = productResults.Concat(cusResult).ToList();
            return View(results);
        }


        public IActionResult ExportDailyReport(DateTime date)
        {

Web-ban-hang/Areas/Admin/Views/DataBoard/Index.cshtml
@model IEnumerable<Web_ban_hang.ViewModels.InvoiceVM>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
	<a asp-controller="DataBoard" asp-action="ExportDailyReport" asp-route-date="@DateTime.Now.Date" class="btn btn-success">
		Export Daily Report
	</a>
</div>

<!-- Sale & Revenue Start -->
<div class="container-fluid pt-4 px-4">
	<div class="row g-4">
		<div class="col-sm-6 col-xl-3">
			<div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
				<i class="fa fa-chart-line fa-3x text-primary"></i>
				<div class="ms-3">
					<p class="mb-2">Doanh thu ngày</p>
					<h6 class="mb-0">$@ViewBag.Todaysale</h6>
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-xl-3">
			<div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
				<i class="fa fa-chart-bar fa-3x text-primary"></i>
				<div class="ms-3">
					<p class="mb-2">Tổng doanh thu</p>
					<h6 class="mb-0">$@ViewBag.Totalsale.ToString("F2")</h6>
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-xl-3">
			<div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
				<i class="fa fa-chart-area fa-3x text-primary"></i>
				<div class="ms-3">
					<p class="mb-2">Tổng mặt hàng bán</p>
					<h6 class="mb-0">@ViewBag.SoHH</h6>
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-xl-3">
			<div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
				<i class="fa fa-chart-pie fa-3x text-primary"></i>
				<div class="ms-3">
					<p class="mb-2">Tổng đơn trong ngày</p>
					<h6 class="mb-0">@ViewBag.TotalOrder</h6>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Sale & Revenue End -->
<!-- Sales Chart Start -->
<div class="container-fluid pt-4 px-4">
	<div class="row g-4">
		<div class="col-sm-12 col-xl-6">
			<div class="bg-light text-center rounded p-4">
				<div class="d-flex align-items-center justify-content-between mb-4">
					<h6 class="mb-0">Worldwide Sales</h6>
					<a href="">Show All</a>
				</div>
				<canvas id="worldwide-sales"></canvas>
			</div>
		</div>
		<div class="col-sm-12 col-xl-6">
			<div class="bg-light text-center rounded p-4">
				<div class="d-flex align-items-center justify-content-between mb-4">
					<h6 class="mb-0">Salse & Revenue</h6>
					<a href="">Show All</a>
				</div>
				<canvas id="salse-revenue"></canvas>
			</div>
		</div>
	</div>
</div>
<!-- Sales Chart End -->
<!-- Recent Sales Start -->
<div class="container-fluid pt-4 px-4">
	<div class="bg-light text-center rounded p-4">
		<div class="d-flex align-items-center justify-content-between mb-4">
			<h6 class="mb-0">Đơn hàng gần đây</h6>
			<a asp-area="Admin" asp-controller="DataBoard" asp-action="InvoiceDetail">Xem tất cả</a>
		</div>
		<div class="table-responsive">
			<table class="table text-start align-middle table-bordered table-hover mb-0">
				<thead>
					<tr class="text-dark">
						<th scope="col"><input class="form-check-input" type="checkbox"></th>
						<th scope="col">Ngày</th>
						<th scope="col">Số hóa đơn</th>
						<th scope="col">Khách hàng</th>
						<th scope="col">Tổng tiền</th>
						<th scope="col">Trạng thái</th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							<td><input class="form-check-input" type="checkbox"></td>
							<td>@item.NgayDat</td>
							<td>@item.MaHD</td>
							<td>@item.HoTen</td>
							<td>@item.TongTien</td>
							<td>Chờ xác nhận</td>
							<td><a class="btn btn-sm btn-primary" asp-area="admin" asp-controller="DataBoard" asp-action="ViewOrder" asp-route-id="@item.MaHD">Xác nhận</a></td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>
<!-- Recent Sales End -->
<!-- Widgets Start -->
<div class="container-fluid pt-4 px-4">
	<div class="row g-4">
		<div class="col-sm-12 col-md-6 col-xl-4">
			<div class="h-100 bg-light rounded p-4">
				<div class="d-flex align-items-center justify-content-between mb-2">
					<h6 class="mb-0">Messages</h6>
					<a href="">Show All</a>
				</div>
				<div class="d-flex align-items-center border-bottom py-3">
					<img class="rounded-circle flex-shrink-0" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
					<div class="w-100 ms-3">
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-0">Jhon Doe</h6>
							<small>15 minutes ago</small>
						</div>
						<span>Short message goes here...</span>
					</div>
				</div>
				<div class="d-flex align-items-center border-bottom py-3">
					<img class="rounded-circle flex-shrink-0" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
					<div class="w-100 ms-3">
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-0">Jhon Doe</h6>
							<small>15 minutes ago</small>
						</div>
						<span>Short message goes here...</span>
					</div>
				</div>
				<div class="d-flex align-items-center border-bottom py-3">
					<img class="rounded-circle flex-shrink-0" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
					<div class="w-100 ms-3">
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-0">Jhon Doe</h6>
							<small>15 minutes ago</small>
						</div>
						<span>Short message goes here...</span>
					</div>
				</div>
				<div class="d-flex align-items-center pt-3">
					<img class="rounded-circle flex-shrink-0" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
					<div class="w-100 ms-3">
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-0">Jhon Doe</h6>
							<small>15 minutes ago</small>
						</div>
						<span>Short message goes here...</span>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-12 col-md-6 col-xl-4">
			<div class="h-100 bg-light rounded p-4">
				<div class="d-flex align-items-center justify-content-between mb-4">
					<h6 class="mb-0">Calender</h6>
					<a href="">Show All</a>
				</div>
				<div id="calender"></div>
			</div>
		</div>
		<div class="col-sm-12 col-md-6 col-xl-4">
			<div class="h-100 bg-light rounded p-4">
				<div class="d-flex align-items-center justify-content-between mb-4">
					<h6 class="mb-0">To Do List</h6>
					<a href="">Show All</a>
				</div>
				<div class="d-flex mb-2">
					<input class="form-control bg-transparent" type="text" placeholder="Enter task">
					<button type="button" class="btn btn-primary ms-2">Add</button>
				</div>
				<div class="d-flex align-items-center border-bottom py-2">
					<input class="form-check-input m-0" type="checkbox">
					<div class="w-100 ms-3">
						<div class="d-flex w-100 align-items-center justify-content-between">
							<span>Short task goes here...</span>
							<button class="btn btn-sm"><i class="fa fa-times"></i></button>
						</div>
					</div>
				</div>
				<div class="d-flex align-items-center border-bottom py-2">
					<input class="form-check-input m-0" type="checkbox">
					<div class="w-100 ms-3">
						<div class="d-flex w-100 align-items-center justify-content-between">
							<span>Short task goes here...</span>
							<button class="btn btn-sm"><i class="fa fa-times"></i></button>
						</div>
					</div>
				</div>
				<div class="d-flex align-items-center border-bottom py-2">
					<input class="form-check-input m-0" type="checkbox" checked>
					<div class="w-100 ms-3">
						<div class="d-flex w-100 align-items-center justify-content-between">
							<span><del>Short task goes here...</del></span>
							<button class="btn btn-sm text-primary"><i class="fa fa-times"></i></button>
						</div>
					</div>
				</div>
				<div class="d-flex align-items-center border-bottom py-2">
					<input class="form-check-input m-0" type="checkbox">
					<div class="w-100 ms-3">
						<div class="d-flex w-100 align-items-center justify-content-between">
							<span>Short task goes here...</span>
							<button class="btn btn-sm"><i class="fa fa-times"></i></button>
						</div>
					</div>
				</div>
				<div class="d-flex align-items-center pt-2">
					<input class="form-check-input m-0" type="checkbox">
					<div class="w-100 ms-3">
						<div class="d-flex w-100 align-items-center justify-content-between">
							<span>Short task goes here...</span>
							<button class="btn btn-sm"><i class="fa fa-times"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Widgets End -->


<script>
		// Dữ liệu từ ViewBag
		var labels2 = @Html.Raw(Json.Serialize(ViewBag.LabelsC2));
		var data2 = @Html.Raw(Json.Serialize(ViewBag.DataC2));

		// Cấu hình biểu đồ
			var ctx = document.getElementById('salse-revenue').getContext('2d');
		var revenueChart = new Chart(ctx, {
			type: 'line', // Loại biểu đồ
			data: {
				labels: labels2, // Nhãn x-axis (ngày)
				datasets: [{
					label: 'Doanh thu theo ngày (VNĐ)', // Tên biểu đồ
					data: data2, // Dữ liệu doanh thu
					backgroundColor: 'rgba(54, 162, 235, 0.6)', // Màu nền
					borderColor: 'rgba(54, 162, 235, 1)', // Màu viền
					borderWidth: 1 // Độ dày viền
				}]
			},
			options: {
				responsive: true,
				plugins: {
					legend: {
						display: true,
						position: 'top'
					}
				},
				scales: {
					y: {
						beginAtZero: true // Bắt đầu từ 0
					}
				}
			}
		});

		// Dữ liệu từ ViewBag
		var labels = @Html.Raw(Json.Serialize(ViewBag.Labels));
		var data = @Html.Raw(Json.Serialize(ViewBag.Data));

		// Cấu hình biểu đồ
			var ctx = document.getElementById('worldwide-sales').getContext('2d');
		var revenueChart = new Chart(ctx, {
			type: 'bar', // Loại biểu đồ
			data: {
				labels: labels, // Nhãn x-axis (ngày)
				datasets: [{
					label: 'Doanh thu theo ngày (VNĐ)', // Tên biểu đồ
					data: data, // Dữ liệu doanh thu
					backgroundColor: 'rgba(54, 162, 235, 0.6)', // Màu nền
					borderColor: 'rgba(54, 162, 235, 1)', // Màu viền
					borderWidth: 1 // Độ dày viền
				}]
			},
			options: {
				responsive: true,
				plugins: {
					legend: {
						display: true,
						position: 'top'
					}
				},
				scales: {
					y: {
						beginAtZero: true // Bắt đầu từ 0
					}
				}
			}
		});

</script>

Web-ban-hang/Areas/Admin/Views/DataBoard/InvoiceDetail.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IPagedList<Web_ban_hang.ViewModels.InvoiceVM>

@{
    ViewData["Title"] = "InvoiceDetail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    int i = 1;

    if(ViewBag.page > 1)
    {
         i = 1 + ViewBag.page* 10;

    }
}
<meta charset="UTF-8">

<table class="table table-hover">
    <thead>
        <tr>
            
            <th scope="col">#</th>
            <th scope="col">Số hóa đơn</th>
            <th scope="col">Khách hàng</th>
            <th scope="col">Ngày đặt</th>
            <th scope="col">Ngày cần</th>
            <th scope="col">Trạng thái</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <th scope="row">@i</th>
                <td><a asp-area="admin" asp-controller="DataBoard" asp-action="ViewOrder" asp-route-id="@item.MaHD">@item.MaHD</a></td>
                <td>@item.HoTen</td>
                <td>@item.NgayDat</td>
                <td>@item.NgayCan</td>
               
                    @if (@item.TrangThai == 1)
                    {
                    <td>Đang giao</td>
                } else
                {
                    <td>Chờ xác nhận</td>
                }

                 

                @if(item.TrangThai == 1)
                {
                    <td><a type="button" class="btn btn-warning" asp-area="admin" asp-controller="DataBoard" asp-action="ViewOrder" asp-route-id="@item.MaHD">Xác nhận</a></td>
                } else
                {
                    <td><a class="btn btn-sm btn-primary" asp-area="admin" asp-controller="DataBoard" asp-action="ViewOrder" asp-route-id="@item.MaHD">Detail</a></td>

                }

               
            </tr>
            i++;
        }
       
    </tbody>
 </table>

@if (TempData["Message"] != null)
{
    <script>
        alert('@TempData["Message"]');
    </script>
}



<div class="pagination">
    @Html.PagedListPager(Model, page => Url.Action("InvoiceDetail","DataBoard", new { page }))
</div>

Web-ban-hang/Areas/Admin/Views/DataBoard/Product.cshtml
@model IEnumerable<Web_ban_hang.ViewModels.ChiTietHangHoaVM>

@{
    ViewData["Title"] = "Product";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    int i = 1;
}

<h1>Product</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Tên sản phẩm</th>
            <th scope="col">Loại</th>
            <th scope="col">Giá</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <th scope="row">@i</th>
            <td>@item.TenHH</td>
            <td>@item.TenLoai</td>
            <td>@item.DonGia</td>
            </tr>
            i++;
        }
       
    </tbody>
</table>