Web-ban-hang/Models/Entities/HangHoa.cs
using System;
using System.Collections.Generic;

namespace Web_ban_hang.Models.Entities
{
    public partial class HangHoa
    {
        public HangHoa()
        {
            BanBes = new HashSet<BanBe>();
            ChiTietHds = new HashSet<ChiTietHd>();
            YeuThiches = new HashSet<YeuThich>();
        }

        public int MaHh { get; set; }
        public string TenHh { get; set; } = null!;
        public string? TenAlias { get; set; }
        public int MaLoai { get; set; }
        public string? MoTaDonVi { get; set; }
        public double? DonGia { get; set; }
        public string? Hinh { get; set; }
        public DateTime NgaySx { get; set; }
        public double GiamGia { get; set; }
        public int SoLanXem { get; set; }
        public string? MoTa { get; set; }
        public string MaNcc { get; set; } = null!;
        public bool TrangThai { get; set; }

        public virtual Loai MaLoaiNavigation { get; set; } = null!;
        public virtual NhaCungCap MaNccNavigation { get; set; } = null!;
        public virtual ICollection<BanBe> BanBes { get; set; }
        public virtual ICollection<ChiTietHd> ChiTietHds { get; set; }
        public virtual ICollection<YeuThich> YeuThiches { get; set; }
    }
}

Web-ban-hang/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Web_ban_hang.Models.Entities;
using Web_ban_hang.ViewModels;
using Web_ban_hang.Helpers;
using Web_ban_hang.Services;

namespace Web_ban_hang.Controllers
{
    public class CartController : Controller
    {
        private readonly HDangShopContext db; // Để sử dụng context
        private readonly ICartService _cartService; // Để sử dụng service

        // Constructor duy nhất kết hợp cả hai tham số
        public CartController(HDangShopContext context, ICartService cartService)
        {
            db = context;
            _cartService = cartService;
        }


        const string CART_KEY = "MYCART";
        public List<CartItem> Cart => HttpContext.Session.Get<List<CartItem>>(CART_KEY) ?? new List<CartItem>();
        public IActionResult Index()
        {
            int cartItemCount = TotalCart();
            _cartService.SetCartItemCount(cartItemCount);
            return View(Cart);
        }
        public IActionResult AddToCart(int id, int quantity = 1)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item == null)
            {
                var hangHoa = db.HangHoas.SingleOrDefault(p => p.MaHh == id);
                if (hangHoa == null)
                {
                    TempData["Message"] = $"Không tìm thấy hàng hóa có mã {id}";
                    return Redirect("/404");
                }
                item = new CartItem
                {
                    MaHh = hangHoa.MaHh,
                    TenHh = hangHoa.TenHh,
                    DonGia = hangHoa.DonGia ?? 0,
                    Hinh = hangHoa.Hinh ?? string.Empty,
                    SoLuong = quantity

                };
                gioHang.Add(item);
            }
            else
            {
                item.SoLuong += quantity;
            }
            HttpContext.Session.Set(CART_KEY,gioHang);
            return RedirectToAction("Index");
        }
        public IActionResult Remove(int id)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                gioHang.Remove(item);
                HttpContext.Session.Set(CART_KEY, gioHang);

            }
            return RedirectToAction("Index");

        }
        public IActionResult Minus(int id)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                item.SoLuong--;
                HttpContext.Session.Set(CART_KEY, gioHang);

            }
            return RedirectToAction("Index");

        }
        public int TotalCart()
        {
            // nếu muốn trả về tất cả số lượng của các loại trong giổ hàg
            //var soluong = Cart.Sum(p => p.SoLuong);
            //return soluong;


            // trả về số loại hàng
            return Cart.Count;
        }      
    }
}

Web-ban-hang/Controllers/HangHoaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web_ban_hang.Models.Entities;
using Web_ban_hang.ViewModels;
using X.PagedList.Extensions;

namespace Web_ban_hang.Controllers
{
    public class HangHoaController : Controller
    {
        private readonly HDangShopContext db;

        public HangHoaController(HDangShopContext context) => db = context;
        public IActionResult Index(int? loai,int? sortList, int? page)
        {
            ViewBag.Loai = loai;
            var hangHoas = db.HangHoas.AsQueryable().Where(p => p.TrangThai == true);

            if (loai.HasValue)
            {
                hangHoas = hangHoas.Where(p => p.MaLoai == loai.Value);
            }
            switch (sortList)
            {
                case 1:
                    hangHoas = hangHoas.OrderBy(p => p.TenHh);
                    ViewBag.SortList = sortList;
                    break;
                case 2:
                    hangHoas = hangHoas.OrderBy(p => p.DonGia);
                    ViewBag.SortList = sortList;
                    break;
                case 3:
                    hangHoas = hangHoas.OrderByDescending(p => p.DonGia);
                    ViewBag.SortList = sortList;
                    break;
                default:
                    break;
            }
                    var result = hangHoas.Select( p => new HangHoaVM
            {
                MaHH = p.MaHh,
                TenHH = p.TenHh,
                DonGia = p.DonGia ?? 0,
                Hinh = p.Hinh ?? "",
                MoTaNgan = p.MoTaDonVi ?? "",
                 TenLoai = p.MaLoaiNavigation.TenLoai

            });

            // Thực hiện phân trang
            int pageSize = 9; // Số sản phẩm trên mỗi trang
            int pageNumber = page ?? 1; // Trang hiện tại, mặc định là trang 1
            var pagedResult = result.ToPagedList(pageNumber, pageSize);

            return View(pagedResult);

            //return View(result);
        }
        public IActionResult Search(string? query)
        {
            var hangHoas = db.HangHoas.AsQueryable();

            if (query != null)
            {
                hangHoas = hangHoas.Where(p => p.TenHh.Contains(query));
            }

            var result = hangHoas.Select(p => new HangHoaVM
            {
                MaHH = p.MaHh,
                TenHH = p.TenHh,
                DonGia = p.DonGia ?? 0,
                Hinh = p.Hinh ?? "",
                MoTaNgan = p.MoTaDonVi ?? "",
                TenLoai = p.MaLoaiNavigation.TenLoai

            });
            return View(result);
        }

        public IActionResult Detail(int id)
        {

            var data = db.HangHoas
                .Include(p => p.MaLoaiNavigation)
                .SingleOrDefault(p => p.MaHh == id);

            ViewBag.RelateProduct = db.HangHoas.Where(p => p.MaLoai == data.MaLoai).OrderByDescending(p => p.MaHh).Take(8).Select(l => new { l.TenHh, l.MoTaDonVi, l.DonGia, l.Hinh, l.MaHh }).ToList();


            if (data == null)
            {
                TempData["Message"] = "Không thấy sản phẩm có mã";
                return Redirect("/404");
            }
            var result = new ChiTietHangHoaVM
            {
                MaHH =data.MaHh,
                TenHH =data.TenHh,
                DonGia = data.DonGia ?? 0,
                ChiTiet = data.MoTa ?? string.Empty,
                Hinh = data.Hinh ?? string.Empty,
                MoTaNgan = data.MoTaDonVi ?? string.Empty,  
                TenLoai = data.MaLoaiNavigation.TenLoai,
                SoLuongTon = 10,
                DiemDanhGia = 5
            };
            return View(result);
        }
    }
}

Web-ban-hang/Views/HangHoa/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IPagedList<Web_ban_hang.ViewModels.HangHoaVM>

@{
	ViewData["Title"] = "Index";
	Layout = "_DanhSachHangHoa";
}



<!-- Single Page Header start -->
@section BreadCrum {
	<div class="container-fluid page-header py-5">
		<h1 class="text-center text-white display-6">Shop</h1>
		<ol class="breadcrumb justify-content-center mb-0">
			<li class="breadcrumb-item"><a href="#">Home</a></li>
			<li class="breadcrumb-item"><a href="#">Pages</a></li>
			<li class="breadcrumb-item active text-white">Shop</li>
		</ol>
	</div>
}
<!-- Single Page Header End -->
<!-- Fruits Shop Start-->
@* <h2>Có @Model.Count() sản phẩm </h2> *@


@await Html.PartialAsync("ProductItem", Model)



<div class="col-12">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center mt-5">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, loai = ViewBag.Loai, sortList = ViewBag.SortList }),
                     new PagedListRenderOptions
            {
                DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                DisplayLinkToLastPage = PagedListDisplayMode.Always,
                DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                DisplayLinkToNextPage = PagedListDisplayMode.Always,
                DisplayLinkToIndividualPages = true,
                UlElementClasses = new[] { "pagination" },
                LiElementClasses = new[] { "page-item" },
                PageClasses = new[] { "page-link" },
                ActiveLiElementClass = "active"
            })
        </ul>
    </nav>
</div>


<style>
    .pagination {
        display: flex;
        justify-content: center; /* Căn giữa các nút phân trang */
    }

        .pagination .page-item {
            margin: 0 2px; /* Khoảng cách giữa các nút */
        }

    .active {   
        padding : 5px 1px;
    }


</style>

<!-- Fruits Shop End-->

Web-ban-hang/Views/HangHoa/ProductItem.cshtml
@model IEnumerable<Web_ban_hang.ViewModels.HangHoaVM>



@foreach (var item in Model)
{
    <div class="col-md-6 col-lg-6 col-xl-4">
        <div class="rounded position-relative fruite-item">
            <div class="fruite-img">
                <a asp-action="Detail" asp-controller="HangHoa" asp-route-id="@item.MaHH">
                <img src="~/Hinh/HangHoa/@item.Hinh" class="img-fluid w-100 rounded-top" alt="@item.TenHH">
                </a>
            </div>
            <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">@item.TenLoai</div>
            <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                <a asp-action="Detail" asp-controller="HangHoa" asp-route-id="@item.MaHH"><h4>@item.TenHH</h4> </a>
                <p>@item.MoTaNgan</p>
                <div class="d-flex justify-content-between flex-lg-wrap">
                    <p class="text-dark fs-5 fw-bold mb-0">$@item.DonGia vnd</p>
                    <a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.MaHH" class="btn border border-secondary rounded-pill px-3 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Thêm vào giỏ</a>
                </div>
            </div>
        </div>
    </div>
}

Web-ban-hang/Views/HangHoa/Search.cshtml
@model IEnumerable<Web_ban_hang.ViewModels.HangHoaVM>

@{
    ViewData["Title"] = "Search";
    Layout = "_DanhSachHangHoa";
}
 
@await Html.PartialAsync("ProductItem", Model)


<div class="col-12">
    <div class="pagination d-flex justify-content-center mt-5">
        <a href="#" class="rounded">&laquo;</a>
        <a href="#" class="active rounded">1</a>
        <a href="#" class="rounded">2</a>
        <a href="#" class="rounded">3</a>
        <a href="#" class="rounded">4</a>
        <a href="#" class="rounded">5</a>
        <a href="#" class="rounded">6</a>
        <a href="#" class="rounded">&raquo;</a>
    </div>
</div>