Web-ban-hang/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Web_ban_hang.Models.Entities;
using Web_ban_hang.ViewModels;
using Web_ban_hang.Helpers;
using Web_ban_hang.Services;

namespace Web_ban_hang.Controllers
{
    public class CartController : Controller
    {
        private readonly HDangShopContext db; // Để sử dụng context
        private readonly ICartService _cartService; // Để sử dụng service

        // Constructor duy nhất kết hợp cả hai tham số
        public CartController(HDangShopContext context, ICartService cartService)
        {
            db = context;
            _cartService = cartService;
        }


        const string CART_KEY = "MYCART";
        public List<CartItem> Cart => HttpContext.Session.Get<List<CartItem>>(CART_KEY) ?? new List<CartItem>();
        public IActionResult Index()
        {
            int cartItemCount = TotalCart();
            _cartService.SetCartItemCount(cartItemCount);
            return View(Cart);
        }
        public IActionResult AddToCart(int id, int quantity = 1)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item == null)
            {
                var hangHoa = db.HangHoas.SingleOrDefault(p => p.MaHh == id);
                if (hangHoa == null)
                {
                    TempData["Message"] = $"Không tìm thấy hàng hóa có mã {id}";
                    return Redirect("/404");
                }
                item = new CartItem
                {
                    MaHh = hangHoa.MaHh,
                    TenHh = hangHoa.TenHh,
                    DonGia = hangHoa.DonGia ?? 0,
                    Hinh = hangHoa.Hinh ?? string.Empty,
                    SoLuong = quantity

                };
                gioHang.Add(item);
            }
            else
            {
                item.SoLuong += quantity;
            }
            HttpContext.Session.Set(CART_KEY,gioHang);
            return RedirectToAction("Index");
        }
        public IActionResult Remove(int id)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                gioHang.Remove(item);
                HttpContext.Session.Set(CART_KEY, gioHang);

            }
            return RedirectToAction("Index");

        }
        public IActionResult Minus(int id)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                item.SoLuong--;
                HttpContext.Session.Set(CART_KEY, gioHang);

            }
            return RedirectToAction("Index");

        }
        public int TotalCart()
        {
            // nếu muốn trả về tất cả số lượng của các loại trong giổ hàg
            //var soluong = Cart.Sum(p => p.SoLuong);
            //return soluong;


            // trả về số loại hàng
            return Cart.Count;
        }      
    }
}

Web-ban-hang/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Web_ban_hang.Helpers;
using Web_ban_hang.Models.Entities;
using Web_ban_hang.Repository;
using Web_ban_hang.ViewModels;

namespace Web_ban_hang.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly HDangShopContext _context; // Để sử dụng context
        private readonly IEmailSender _emailSender;

        public CheckoutController(HDangShopContext db, IEmailSender emailSender)
        {
            _context = db;
            _emailSender = emailSender;
        }
        public async Task<IActionResult> CreateInvoice()
        {
            string customerId = HttpContext.User.FindFirst("CustomerID")?.Value;

            var data = _context.KhachHangs.FirstOrDefault(p => p.MaKh == customerId);

            var gioHang = HttpContext.Session.Get<List<CartItem>>("MYCART");




            var hoaDon = new HoaDon
            {
                NgayDat = DateTime.Now,
                MaKh = customerId,
                DiaChi = data.DiaChi,
                CachThanhToan = "Cash",
                CachVanChuyen = "Airline",
                PhiVanChuyen = 0,
                MaTrangThai = 1,
                GhiChu = "note"

            };

            _context.HoaDons.Add(hoaDon);
            _context.SaveChanges();

            int Mahdnew = hoaDon.MaHd;

            foreach (var item in gioHang)
            {
                var orderdetails = new ChiTietHd
                {
                    MaHd = Mahdnew,
                    MaHh = item.MaHh,
                    DonGia = item.DonGia,
                    SoLuong = item.SoLuong,
                    GiamGia = 0
                };


                _context.ChiTietHds.Add(orderdetails);
                _context.SaveChanges();
            }




            HttpContext.Session.Remove("MYCART");


            var receive = User.FindFirst((ClaimTypes.Email)).Value;
            var subject = "Thư cảm ơn";
            var message = "Cảm ơn bạn đã đặt hàng của chúng tôi, đơn hàng sẽ sớm được chuẩn bị và vận chuyển đến cho bạn!!";

            await _emailSender.SendEmailAsync(receive, subject, message);

            TempData["Success"] = "Cảm ơn bạn, Đơn đã được đặt hàng thành công!";

            return RedirectToAction("index", "Home");
        }

        [Authorize]
        public IActionResult Ordering()
        {
            var MaKh = User.FindFirst("CustomerID").Value;

            var data = _context.ChiTietHds.Include(p => p.MaHdNavigation).Include(p => p.MaHhNavigation).Where(p => p.MaHdNavigation.MaKh == MaKh && p.MaHdNavigation.MaTrangThai != 3).ToList();

            var result = data.Select(item => new Order
            {
				maHD = item.MaHd,
				maCT = item.MaCt,
                MaHh = item.MaHh,
                Hinh = item.MaHhNavigation.Hinh,
                TenHh = item.MaHhNavigation.TenHh,
                SoLuong = item.SoLuong,
                DonGia = item.DonGia,
                TrangThai = item.MaHdNavigation.MaTrangThai,

            });

			return View(result);
        }
        [Authorize]
        public IActionResult Ordered()
        {
            var MaKh = User.FindFirst("CustomerID").Value;

            var data = _context.ChiTietHds.Include(p => p.MaHdNavigation).Include(p => p.MaHhNavigation).Where(p => p.MaHdNavigation.MaKh == MaKh && p.MaHdNavigation.MaTrangThai == 3).ToList();

            var result = data.Select(item => new Order
            {
                maHD = item.MaHd,
                MaHh = item.MaHh,
                Hinh = item.MaHhNavigation.Hinh,
                TenHh = item.MaHhNavigation.TenHh,
                SoLuong = item.SoLuong,
                DonGia = item.DonGia,
                TrangThai = item.MaHdNavigation.MaTrangThai,
                NgayGiao = item.MaHdNavigation.NgayGiao,
            });

			return View(result);
        }

        public IActionResult Confirm(int id)
        {
			var hoaDon = _context.HoaDons.SingleOrDefault(hd => hd.MaHd == id);

			if (hoaDon == null)
			{
				// Nếu không tìm thấy hóa đơn, trả về lỗi hoặc thông báo
				TempData["Error"] = $"Không tìm thấy hóa đơn với mã {id}";
				return RedirectToAction("Index", "Cart");
			}

			// Cập nhật mã trạng thái
			hoaDon.MaTrangThai = 3;
            hoaDon.NgayGiao = DateTime.Now;

			// Lưu thay đổi vào cơ sở dữ liệu
			_context.SaveChanges();

			// Thông báo thành công
			TempData["Success"] = "Cảm ơn về đơn hàng của bạn!";
			return RedirectToAction("Index", "Home");
        }

        public IActionResult Remove(int id)
        {
            var pro = _context.HoaDons.SingleOrDefault(p => p.MaHd == id);

            pro.MaTrangThai = 3;
            _context.SaveChanges();
            return RedirectToAction("index", "home");
        }


    }
}

Web-ban-hang/Controllers/HangHoaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web_ban_hang.Models.Entities;
using Web_ban_hang.ViewModels;
using X.PagedList.Extensions;

namespace Web_ban_hang.Controllers
{
    public class HangHoaController : Controller
    {
        private readonly HDangShopContext db;

        public HangHoaController(HDangShopContext context) => db = context;
        public IActionResult Index(int? loai,int? sortList, int? page)
        {
            ViewBag.Loai = loai;
            var hangHoas = db.HangHoas.AsQueryable().Where(p => p.TrangThai == true);

            if (loai.HasValue)
            {
                hangHoas = hangHoas.Where(p => p.MaLoai == loai.Value);
            }
            switch (sortList)
            {
                case 1:
                    hangHoas = hangHoas.OrderBy(p => p.TenHh);
                    ViewBag.SortList = sortList;
                    break;
                case 2:
                    hangHoas = hangHoas.OrderBy(p => p.DonGia);
                    ViewBag.SortList = sortList;
                    break;
                case 3:
                    hangHoas = hangHoas.OrderByDescending(p => p.DonGia);
                    ViewBag.SortList = sortList;
                    break;
                default:
                    break;
            }
                    var result = hangHoas.Select( p => new HangHoaVM
            {
                MaHH = p.MaHh,
                TenHH = p.TenHh,
                DonGia = p.DonGia ?? 0,
                Hinh = p.Hinh ?? "",
                MoTaNgan = p.MoTaDonVi ?? "",
                 TenLoai = p.MaLoaiNavigation.TenLoai

            });

            // Thực hiện phân trang
            int pageSize = 9; // Số sản phẩm trên mỗi trang
            int pageNumber = page ?? 1; // Trang hiện tại, mặc định là trang 1
            var pagedResult = result.ToPagedList(pageNumber, pageSize);

            return View(pagedResult);

            //return View(result);
        }
        public IActionResult Search(string? query)
        {
            var hangHoas = db.HangHoas.AsQueryable();

            if (query != null)
            {
                hangHoas = hangHoas.Where(p => p.TenHh.Contains(query));
            }

            var result = hangHoas.Select(p => new HangHoaVM
            {
                MaHH = p.MaHh,
                TenHH = p.TenHh,
                DonGia = p.DonGia ?? 0,
                Hinh = p.Hinh ?? "",
                MoTaNgan = p.MoTaDonVi ?? "",
                TenLoai = p.MaLoaiNavigation.TenLoai

            });
            return View(result);
        }

        public IActionResult Detail(int id)
        {

            var data = db.HangHoas
                .Include(p => p.MaLoaiNavigation)
                .SingleOrDefault(p => p.MaHh == id);

            ViewBag.RelateProduct = db.HangHoas.Where(p => p.MaLoai == data.MaLoai).OrderByDescending(p => p.MaHh).Take(8).Select(l => new { l.TenHh, l.MoTaDonVi, l.DonGia, l.Hinh, l.MaHh }).ToList();


            if (data == null)
            {
                TempData["Message"] = "Không thấy sản phẩm có mã";
                return Redirect("/404");
            }
            var result = new ChiTietHangHoaVM
            {
                MaHH =data.MaHh,
                TenHH =data.TenHh,
                DonGia = data.DonGia ?? 0,
                ChiTiet = data.MoTa ?? string.Empty,
                Hinh = data.Hinh ?? string.Empty,
                MoTaNgan = data.MoTaDonVi ?? string.Empty,  
                TenLoai = data.MaLoaiNavigation.TenLoai,
                SoLuongTon = 10,
                DiemDanhGia = 5
            };
            return View(result);
        }
    }
}

Web-ban-hang/ViewComponents/ListSaleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Web_ban_hang.Models.Entities;
using Web_ban_hang.ViewModels;

namespace Web_ban_hang.ViewComponents
{
    public class ListSaleViewComponent : ViewComponent
    {
        private readonly HDangShopContext db;

        public ListSaleViewComponent(HDangShopContext context) => db = context;

        public IViewComponentResult Invoke()
        {
            var data = db.HangHoas.Select(Loai => new ListSale
            {
                TenLoai = Loai.TenHh,
                Hinh = Loai.Hinh,
                DonGia = Loai.DonGia ?? 0,
            }).OrderBy(p => p.TenLoai);
            return View(data);
        }
    }
}

Web-ban-hang/Views/Shared/_DanhSachHangHoa.cshtml
@{
	Layout = "_LayoutCustomer";
}
@{
    var item = ViewBag.Loai;
}
<!-- Single Page Header start -->
@RenderSection("BreadCrum", required: false)

<!-- Single Page Header End -->
<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
    <div class="container py-5">
        <h1 class="mb-4">HDang Shop</h1>
        <div class="row g-4">
            <div class="col-lg-12">
                <div class="row g-4">
                    <div class="col-xl-3">
                        <div class="input-group w-100 mx-auto d-flex">
                            @await Html.PartialAsync("_TimKiem")
                        </div>
                    </div>
                    <div class="col-6"></div>
                    <div class="col-xl-3">
                            <div class="bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4">                      
                                <label for="fruits">Default Sorting:</label>
                          

                            <form method="get" asp-action="Index" asp-controller="HangHoa">
                                <input type="hidden" name="loai" value="@ViewBag.Loai" />
                                <select id="fruits" name="sortList" class="border-0 form-select-sm bg-light me-3" onchange="this.form.submit()">
                                    <option value="1">Nothing</option>
                                    <option value="2">Price</option>
                                    <option value="3">Des price</option>
                                    <option value="4"></option>
                                </select>
                            </form>

                        </div>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-lg-3">
                        <div class="row g-4">

                            @await Component.InvokeAsync("MenuLoai")

                            <div class="col-lg-12">
                                <div class="mb-3">
                                    <h4 class="mb-2">Price</h4>
                                    <input type="range" class="form-range w-100" id="rangeInput" name="rangeInput" min="0" max="500" value="0" oninput="amount.value=rangeInput.value">
                                    <output id="amount" name="amount" min-velue="0" max-value="500" for="rangeInput">0</output>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="mb-3">
                                    <h4>Additional</h4>
                                    <div class="mb-2">
                                        <input type="radio" class="me-2" id="Categories-1" name="Categories-1" value="Beverages">
                                        <label for="Categories-1"> Organic</label>
                                    </div>
                                    <div class="mb-2">
                                        <input type="radio" class="me-2" id="Categories-2" name="Categories-1" value="Beverages">
                                        <label for="Categories-2"> Fresh</label>
                                    </div>
                                    <div class="mb-2">
                                        <input type="radio" class="me-2" id="Categories-3" name="Categories-1" value="Beverages">
                                        <label for="Categories-3"> Sales</label>
                                    </div>
                                    <div class="mb-2">
                                        <input type="radio" class="me-2" id="Categories-4" name="Categories-1" value="Beverages">
                                        <label for="Categories-4"> Discount</label>
                                    </div>
                                    <div class="mb-2">
                                        <input type="radio" class="me-2" id="Categories-5" name="Categories-1" value="Beverages">
                                        <label for="Categories-5"> Expired</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <h4 class="mb-3">Featured products</h4>
                                
                                @await  Component.InvokeAsync("ListSale")

                                <div class="d-flex justify-content-center my-4">
                                    <a href="#" class="btn border border-secondary px-4 py-3 rounded-pill text-primary w-100">Vew More</a>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="position-relative">
                                    <img src="img/banner-fruits.jpg" class="img-fluid w-100 rounded" alt="">
                                    <div class="position-absolute" style="top: 50%; right: 10px; transform: translateY(-50%);">
                                        <h3 class="text-secondary fw-bold">Fresh <br> Fruits <br> Banner</h3>
                                    </div>
                                </div>
                            </div>
                        </div>



                    </div>
                    <div class="col-lg-9">
                        <div class="row g-4 justify-content-center">

                            @RenderBody()
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@* <script>
    document.getElementById('fruits').addEventListener('change', function () {
        var selectedValue = this.value;

        // Thực hiện hành động tùy thuộc vào giá trị được chọn
        if (selectedValue) {
            window.location.href = '/HangHoa/SortByPrice';
        }
    });
</script> *@
<!-- Fruits Shop End-->

Web-ban-hang/Views/Shared/_Footer.cshtml
        <!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
    <div class="container py-5">
        <div class="pb-4 mb-4" style="border-bottom: 1px solid rgba(226, 175, 24, 0.5) ;">
            <div class="row g-4">
                <div class="col-lg-3">
                    <a href="#">
                        <h1 class="text-primary mb-0">Upage</h1>
                        <p class="text-secondary mb-0">All products</p>
                    </a>
                </div>
                <div class="col-lg-6">
                    <div class="position-relative mx-auto">
                        <input class="form-control border-0 w-100 py-3 px-4 rounded-pill" type="number" placeholder="Your Email">
                        <button type="submit" class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white" style="top: 0; right: 0;">Subscribe Now</button>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="d-flex justify-content-end pt-3">
                        <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href="https://www.facebook.com/haidang190604"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-secondary btn-md-square rounded-circle" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Why People Like us!</h4>
                    <p class="mb-4">
                        typesetting, remaining essentially unchanged. It was
                        popularised in the 1960s with the like Aldus PageMaker including of Lorem Ipsum.
                    </p>
                    <a href="" class="btn border-secondary py-2 px-4 rounded-pill text-primary">Read More</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Shop Info</h4>
                    <a class="btn-link" href="">About Us</a>
                    <a class="btn-link" href="">Contact Us</a>
                    <a class="btn-link" href="">Privacy Policy</a>
                    <a class="btn-link" href="">Terms & Condition</a>
                    <a class="btn-link" href="">Return Policy</a>
                    <a class="btn-link" href="">FAQs & Help</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Account</h4>
                    <a asp-action="Login" asp-controller="Databoard" asp-area="Admin" class="btn-link">My Account</a>
                    <a class="btn-link" href="">Shop details</a>
                    <a asp-controller="Cart" asp-action="Index" class="btn-link" >Shopping Cart</a>
                    <a class="btn-link" href="">Wishlist</a>
                    <a class="btn-link" href="">Order History</a>
                    <a class="btn-link" href="">International Orders</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Contact</h4>
                    <p>Address: 450 Lê Văn Việt, Thủ Đức</p>
                    <p>Email: dangd408@gmail.com</p>
                    <p>Phone: +1906 24</p>
                    <p>Payment Accepted</p>
                    <img src="img/payment.png" class="img-fluid" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

Web-ban-hang/Views/Shared/_LayoutCustomer.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body>
    <div>
        <!-- Spinner Start -->
        <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
            <div class="spinner-grow text-primary" role="status"></div>
        </div>
        <!-- Spinner End -->
        <!-- Navbar start -->
        <div class="container-fluid fixed-top">
            <div class="container topbar bg-primary d-none d-lg-block">
                <div class="d-flex justify-content-between">
                    <div class="top-info ps-2">
                        <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">450 Lê Văn Việt, Thủ Đức</a></small>
                        <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">dangd408@gmail.com</a></small>
                    </div>
                    <div class="top-link pe-2">
                        <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
                        <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
                        <a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
                    </div>
                </div>
            </div>
            <div class="container px-0">
                <nav class="navbar navbar-light bg-white navbar-expand-xl">
                    <a href="/" class="navbar-brand"><h1 class="text-primary display-6">Upage</h1></a>
                    <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="fa fa-bars text-primary"></span>
                    </button>
                    <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                        <div class="navbar-nav mx-auto">
                            <a href="/" class="nav-item nav-link active">Home</a>
                            <a asp-action="Index" asp-controller="HangHoa" class="nav-item nav-link">Shop</a>
                            <a href="~/HangHoa/Detail/1086" class="nav-item nav-link">Shop Detail</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu m-0 bg-secondary rounded-0">
                                    <a asp-action="Index" asp-controller="Cart" class="dropdown-item">Giỏ hàng</a>
                                    @if (User.Identity?.IsAuthenticated ?? false)
                                    {
                                        <a asp-action="Ordering" asp-controller="Checkout" class="dropdown-item">Đang giao</a>
                                        <a asp-action="Ordered" asp-controller="Checkout" class="dropdown-item">Đã đặt</a>
                                    }
                                </div>
                            </div>
                            <a asp-action="Contact" asp-controller="Home" class="nav-item nav-link">Contact</a>
                        </div>
                        <div class="d-flex m-3 me-0">
                            <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>
                            <a asp-action="Index" asp-controller="Cart"  class="position-relative me-4 my-auto">
                                <i class="fa fa-shopping-bag fa-2x"></i>
                                <span class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1" style="top: -5px; left: 15px; height: 20px; min-width: 20px;">@await Component.InvokeAsync("CartItemCount")</span>
                            </a>

                            @if (User.Identity?.IsAuthenticated ?? false)
                    {
                                <a asp-action="Profile" asp-controller="Customer">Chào, @User.FindFirst("CustomerID")?.Value!</a>
                            
                            } else
                            {
                                <a asp-action="Profile" asp-controller="Customer" class="my-auto">
                                    <i class="fas fa-user fa-2x"></i>
                                </a>
                            }

                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Navbar End -->
        <!-- Modal Search Start -->
        <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-fullscreen">
                <div class="modal-content rounded-0">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex align-items-center">
                        <div class="input-group w-75 mx-auto d-flex">
                            <input id="searchText" type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1">
                            <span id="searchButton" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Search End -->


        <div style="min-height:400px;" class="hero-header">
            @Html.Partial("_Notification")

            @RenderBody()
        </div>


        @await Html.PartialAsync("_Footer")
    </div>


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>

    @RenderSection("Scrips", required: false)

    <script>
        $(document).ready(function () {
            $("#searchButton").click(function () {
                let url = '/HangHoa/Search?query=' + $("#searchText").val();
                window.location.href = url;
            });
        })
    </script>
</body>
</html>

Web-ban-hang/Views/Shared/_TimKiem.cshtml
<form asp-action="Search" asp-controller="HangHoa" style="display:flex ; ">
    <input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1" name="query">
    <button style=" border: none;background-color: #FFFFFF;">
        <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
    </button>
</form>